apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}
    name: {{ .Values.name }}
    app.kubernetes.io/managed-by: "ansible-homelab"
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    app.kubernetes.io/component: "cronjob"
spec:
  schedule: {{ .Values.cron.schedule | quote }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy | default "Forbid" | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: {{ .Values.appName }}
            name: {{ .Values.name }}
            app.kubernetes.io/managed-by: "ansible-homelab"
            app.kubernetes.io/name: {{ .Release.Name | quote }}
            app.kubernetes.io/component: "cronjob"
        spec:
          restartPolicy: {{ .Values.cron.restartPolicy | default "OnFailure" | quote }}
          containers:
            - name: {{ .Values.name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              {{- if .Values.command }}
              command: {{ .Values.command | toJson }}
              {{- end }}
              {{- if .Values.args }}
              args:
                {{- range .Values.args }}
                - {{ . | quote }}
                {{- end }}
              {{- end }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              env:
                - name: "APP_NAME"
                  value: {{ .Values.appName | default .Release.Namespace | quote }}
                {{- if .Values.postgres.enabled }}
                - name: {{ .Values.postgres.db_name_key | quote }}
                  value: {{ .Values.postgres.db_name | default .Values.appName | default .Release.Namespace | quote }}
                - name: {{ .Values.postgres.user_key | quote }}
                  value: {{ .Release.Name | quote }}
                - name: "POSTGRES_HOST"
                  value: {{ .Values.postgres.host | quote }}
                {{- end }}

                # add non sensitive environment variables from values.yaml
                {{- range $key, $val := .Values.env_vars }}
                - name: {{ $key | quote }}
                  value: {{ $val | quote }}
                {{- end }}
              envFrom:
                - secretRef:
                    name: "{{ .Values.appName | default .Release.Namespace }}-secrets"
                {{- if .Values.nats.enabled }}
                - configMapRef:
                    name: {{ .Values.appName }}-shared-config
                {{- end }}
