# STATE
# when set to false, results in app being removed from k3s cluster
enabled: true

# CONFIG
# change to true if this app connects to db, will create database of db_name (defaults to app_name) automatically
# postgres:
  # enabled: false
  # uncomment these and overwrite the group_vars/all.yml settings for app specifics as necessary
  # host:
  # port:
  # db_name:
 
# ingress:
  # enabled: false
  # host: "subdomain.mydomain.com"
  # annotations: 
  #   traefik.ingress.kubernetes.io/router.entrypoints: web

# nats:
#   enabled: false
#   streamName:

env_vars:
  # add non-sensitive environment variables injected into apps environment here
  # NO SECRETS! go to vault.yaml for that
