- name: Configure PN50 hardware power limits
  import_playbook: playbooks/pn50_power_limits.yml
  tags: [hardware]

- name: Setup local registry to hold k3s images
  import_playbook: infrastructure/registry/main.yml
  tags: [infra]

- name: Install K3s Cluster
  import_playbook: infrastructure/k3s/main.yml
  tags: [infra]

- name: Install postgres into K3 container
  import_playbook: infrastructure/postgres/install.yml
  tags: [infra]

