- name: Determine if NATS is needed by any component
  ansible.builtin.set_fact:
    needs_nats: "{{ final_components | selectattr('nats.enabled', 'defined') | selectattr('nats.enabled', 'equalto', true) | list | length > 0 }}"
  run_once: true

# - name: Ensure nats stream exists
#   delegate_to: "{{ groups['nats_node'][0] }}"
#   when: (need_nats | default(false) | bool) and not (is_purge | default(false) | bool)
#   kubernetes.core.helm:
#     name: "{{ app_name }}-infra"
#     chart_ref: "{{ project_root }}/charts/infrastructure/"
#     release_namespace: "{{ app_name }}"
#     create_namespace: true
#     values: "{{ app_overrides }}"
#   run_once: true
- name: Ensure nats stream exists
  delegate_to: localhost
  when: (needs_nats | default(false) | bool) and not (is_purge | default(false) | bool)
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: jetstream.nats.io/v1beta2
      kind: Stream
      metadata:
        name: "{{ app_name }}-stream"
        namespace: "{{ app_name }}"
        labels:
          app: "{{ app_name }}"
          app.kubernetes.io/managed-by: "ansible-homelab"
      spec:
        name: "{{ app_overrides.nats.streamName | default(app_name) }}-stream"
        subjects:
          - "{{ app_overrides.nats.streamName | default(app_name) }}"
          - "{{ app_overrides.nats.streamName | default(app_name) }}.>"
        storage: file

- name: Create Common App Configuration Map
  delegate_to: localhost
  when: (needs_nats | default(false) | bool) and not (is_purge | default(false) | bool)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "{{ app_name }}-shared-config"
        namespace: "{{ app_name }}"
        labels:
          app: "{{ app_name }}"
          app.kubernetes.io/managed-by: "ansible-homelab"
      data:
        NATS_STREAM_NAME: "{{ app_overrides.nats.streamName | default(app_name) }}-stream"
        NATS_SUBJECT_PREFIX: "{{ app_overrides.nats.subjectPrefix | default(app_name) }}"
        NATS_URL: "nats://nats.nats.svc.cluster.local:4222"
  run_once: true
