- name: Terminate active connections for the app user
  community.postgresql.postgresql_query:
    login_db: "postgres"
    query: |
      SELECT pg_terminate_backend(pid)
      FROM pg_stat_activity
      WHERE usename = '{{ app_name }}' AND pid <> pg_backend_pid();
    login_user: "{{ db_super_user | default('postgres') }}"
    login_password: "{{ vault_postgres_password }}"
  delegate_to: "{{ groups['db_servers'][0] }}"

- name: Ensure application database removed
  community.postgresql.postgresql_db:
    name: "{{ helm_vars.db_name | default(app_name) }}"
    owner: "{{ app_name }}"
    state: absent
    login_host: "{{ groups['db_servers'][0] }}"
    login_user: "{{ db_super_user | default('postgres') }}"
    login_password: "{{ vault_postgres_password }}"
    port: "{{ db_node_port | int }}"
  delegate_to: "{{ groups['db_servers'][0] }}"

- name: Clear all global dependencies for the app user
  community.postgresql.postgresql_query:
    login_db: "postgres"
    query: 'DROP OWNED BY "{{ app_name }}" CASCADE;'
    login_user: "{{ db_super_user | default('postgres') }}"
    login_password: "{{ vault_postgres_password }}"
    login_host: "{{ groups['db_servers'][0] }}"
    port: "{{ db_node_port | int }}"
  delegate_to: "{{ groups['db_servers'][0] }}"

- name: Ensure app database user absent
  community.postgresql.postgresql_user:
    name: "{{ app_name }}"
    password: "{{ current_app_pass }}"
    state: absent
    login_host: "{{ groups['db_servers'][0] }}"
    login_user: "{{ db_super_user | default('postgres') }}"
    login_db: "{{ db_initial_name | default('postgres') }}"
    login_password: "{{ vault_postgres_password }}"
    port: "{{ db_node_port | int }}"
  delegate_to: "{{ groups['db_servers'][0] }}"
