# these are loaded as app defaults. keep stuff `enabled: false` by default, override in app specific values.yaml
workloadType: deployment # "cronjob" or "deployment"
replicaCount: 1

enabled: true

image:
  repository: my-repo/my-app
  pullPolicy: Always
  tag: latest

postgres:
  enabled: false
  host: "postgres-service.database.svc.cluster.local"
  port: 5432
  password:
  db_name:
  # environment variables
  db_name_key: "POSTGRES_DB"
  user_key: "POSTGRES_USER"
  pass_key: "POSTGRES_PASSWORD"
  url_key: "POSTGRES_URL"


ingress:
  enabled: false
  host:
  # annotations: 
  #   traefik.ingress.kubernetes.io/router.entrypoints: web

service:
  targetPort: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nats:
  enabled: false
  streamName:

env_vars: []
