apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/managed-by: "ansible-homelab"
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: deployment
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        app: {{ .Release.Name }}
        app.kubernetes.io/managed-by: "ansible-homelab"
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/component: deployment
    spec:
      containers:
      - name: main
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        ports:
          - name: http
            containerPort: {{ .Values.service.targetPort | default 8080 }}
            protocol: TCP
        env:
          - name: APP_NAME
            value: {{ .Release.Name }}
          {{- if .Values.postgres.enabled }}
          - name: {{ .Values.postgres.db_name_key | quote }}
            value: {{ .Values.postgres.db_name | default .Release.Name | quote }}
          - name: {{ .Values.postgres.user_key | quote }}
            value: {{ .Release.Name | quote }}
          - name: "POSTGRES_HOST"
            value: {{ .Values.postgres.host | quote }}
          {{- end }}

          {{- if .Values.nats.enabled }}
          - name: "NATS_STREAM_NAME"
            value: {{ .Values.nats.streamName | default .Release.Name | quote }}
          - name: "NATS_URL"
            value: "nats://nats.nats.svc.cluster.local:4222"
          {{- end }}

          # add non sensitive environment variables from values.yaml
          {{- range $key, $val := .Values.env_vars }}
          - name: {{ $key | quote }}
            value: {{ $val | quote }}
          {{- end }}
        envFrom:
          - secretRef:
              name: "{{ .Release.Name }}-secrets"

      - name: health-sidecar
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache wget
          while true; do
            payload="{\"service\": \"{{ .Release.Name }}\", \"status\": \"running\", \"host\": \"$NODE_NAME\"}"
            wget -q --post-data="$payload" http://{{ .Values.global.controlNodeHost }}:9090/health -O - || true
            sleep 30
          done
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
