apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets" 
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- if and .Values.postgres .Values.postgres.enabled }}
  # for the deployment.yaml env var
  {{ .Values.postgres.pass_key }}: {{ .Values.postgres.password | quote }}
  # passed to app env for connection string
  {{ .Values.postgres.url_key }}: "postgresql://{{ .Release.Name }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.db_name | default .Release.Name }}"
  {{- end }}

  # app specific secrets from apps/myapp/vault.yaml
  {{- range $key, $val := .Values.env_secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
