apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.appName | default .Release.Namespace }}-secrets" 
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
{{- if .Values.postgres.enabled }}
  # for the deployment.yaml env var
  {{ .Values.postgres.pass_key }}: {{ .Values.postgres.password | quote }}
  # passed to app env for connection string
  {{- $dbName := .Values.postgres.db_name | default .Values.appName | default .Release.Namespace }}
  {{- $username := .Values.postgres.username | default .Values.appName | default .Release.Namespace }}
  {{ .Values.postgres.url_key }}: "postgresql://{{ $username }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ $dbName }}"
{{- end }}

  # app specific secrets from apps/myapp/vault.yaml
{{- range $key, $val := .Values.vault_env_secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
